# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jacob Gildenblat
email: jacob.gildenblat@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal tech blog about Deep Learning, Machine Learning and Computer Vision.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jacobgil.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: jacobgildenblat
github_username:  jacobgil

comments:
 provider: disqus
disqus: 
 short_name: jacobgil.github.io

google_analytics: UA-88816088-1
# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax

theme:
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

excerpt_separator: <!--more-->  # you can specify your own separator, of course.